# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestContext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='quest',
            name='QuestStatus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='QuestTypeId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
