# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestContext', '0003_questreports_queststatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestReports',
            new_name='QuestReport',
        ),
    ]
