# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationReportLat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LocationReportLong', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LocationReportTimestamp', models.DateTimeField()),
                ('UserId', models.IntegerField()),
            ],
        ),
    ]
