# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoodReportCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.IntegerField()),
                ('MoodType', models.IntegerField()),
                ('UserText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThoughtDistortionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoughtDistortionReportCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ThoughtDistortionTypeId', models.IntegerField()),
                ('UserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserInterationCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('InitiatorUserId', models.IntegerField()),
                ('RecieverUserIt', models.IntegerField()),
            ],
        ),
    ]
